apiVersion: apps/v1  # The API version of the Kubernetes resource. `apps/v1` indicates it's a Deployment resource in the `apps` API group and the `v1` version.
kind: Deployment  # The type of Kubernetes resource. In this case, it's a Deployment.
metadata:
  name: server-deployment  # The name of the Deployment resource.
spec:
  replicas: 3  # The desired number of pod replicas to run for this Deployment.
  selector:  # Selector to identify the pods controlled by this Deployment.
    matchLabels:
      component: server  # Selector to match pods with labels having `component: web`.
  template:  # Template for creating new pods managed by this Deployment.
    metadata:
      labels:
        component: server  # Labels applied to pods created from this template.
    spec:
      containers:  # List of containers to run in the pods created from this template.
        - name: server  # Name of the container.
          image: dakporhonor/multi-server  # Docker image to use for the container.
          ports:
            - containerPort: 5000  # Port to expose on the container.
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
